---
# tasks file for roller
#
#
#

- name: redhat updates
  yum:
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"

- name: debian updates
  apt:
    name: "*"
    state: latest
  when: ansible_os_family == "Debian"

- name: installing httpd
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"


- name: installing apache2
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: copy index file
  copy:
    src: /home/ansi/index.html
    dest: /var/www/html
    mode: 0777
  notify:
  - start service

- name:
  yum:
    name: java-1.8.0-openjdk
    state: present
  when: ansible_os_family == "RedHat"


- name:
  apt:
    name: openjdk-11-jre
    state: present
  when: ansible_os_family == "Debian"

- name: download tomcat
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.72/bin/apache-tomcat-9.0.72.tar.gz
    dest: /opt
    mode: 0777

- name: untar tomcat
  unarchive:
    src: /opt/apache-tomcat-9.0.72.tar.gz
    dest: /opt
    mode: 0777
  notify:
  - shutdown
  - startup

- name: download war
  get_url:
    url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
    dest: /opt/apache-tomcat-9.0.72/webapps  
    mode: 0777
  notify:
  - shutdown
  - startup    


   
